### ISSUE TITLE
TenantResolver in reactive application

### ISSUE THREAD

**Issue by hrandika** [jzheaux/springone2019#3]
Hi thanks for the great guide.One concern with me how to make the TenantResolver in Reactive context. SecurityContextHolder.getContext() is not reactive. Any way we can manage that with
ReactiveSecurityContextHolder.getContext() ? Thanks in advance. 
What I found in stack-overflow  is [this](https://stackoverflow.com/questions/55800916/multi-tenancy-in-reactive-spring-boot-application-using-mongodb-reactive)

**Comment by jzheaux** [comment]
Yes, you can certainly create a reactive tenant resolver, basing it off of `ReactiveSecurityContextHolder`. It would probably look similar to:

```java
public Mono<String> resolve() {
    return ReactiveSecurityContextHolder.getContext()
            .map(SecurityContext::getAuthentication)
            .filter(authentication -> authentication instanceof AbstractOAuth2AuthenticiationToken)
            .cast(AbstractOAuth2AuthenticationToken.class)
            .map(token -> token.getTokenAttributes().get("tenant_id"))
            .switchIfEmpty(Mono.just("all"));
}
```

Note that currently the use of reactive components in SpEL expressions is limited. You might consider following [this ticket](https://jira.spring.io/browse/DATACMNS-1108) to track progress.
